services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/perguntas.yaml:/docker-entrypoint-initdb.d/perguntas.yaml
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/configs/import_questions.sh:/docker-entrypoint-initdb.d/import_questions.sh
  
  app:
    build: ./app
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    tty: true
    depends_on:
      - db
    command: "tail -f /dev/null"